M48
; DRILL file {KiCad 8.0.6} date 2025-08-08T18:32:25+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-08T18:32:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.1656Y-0.8709
X1.2156Y-2.7709
X3.2156Y-1.0709
X3.2156Y-2.1709
M30
